### ISSUE TITLE
Failing tests on Windows latest

### ISSUE THREAD

**Issue by cmalinmayor** [funkelab/motile#124]
@tlambert03 Do you have a chance to take a look? It seems like a SCIP version update, so probably actually an ilpy problem

**Comment by tlambert03** [comment]
hmm, not immediately sure why this is happening.  a couple observations for now:

- ilpy was hard-pinned to scip 0.9.1 in https://github.com/funkelab/ilpy-feedstock/pull/5 (back in june)
- for some reason, the test in #123 actually [used ilpy 0.3.1](https://github.com/funkelab/motile/actions/runs/11061329125/job/30733712406#step:4:43) instead of the newer (pinned) v0.4 ... but when it was merged to main, it [used ilpy v0.4.0 but weirdly used scip v0.9.1](https://github.com/funkelab/motile/actions/runs/11111094587/job/30870246536#step:4:44).  All I did was rerun the test, and the second time, it solved correctly and used scip v0.9.0 and [everything passed](https://github.com/funkelab/motile/actions/runs/11111094587)

**Comment by cmalinmayor** [comment]
Huh, okay! Good enough for me! Thanks :) I'll try re-running next time before I ping you
